routers:
  inference.tinfoil.sh:
  # router.inf6.tinfoil.sh:
  router.inf7.tinfoil.sh:

models:
  nomic-embed-text:
    repo: tinfoilsh/confidential-nomic-embed-text
    enclaves:
      - nomic-embed-text.inf6.tinfoil.sh

  doc-upload:
    repo: tinfoilsh/confidential-doc-upload
    enclaves:
      - doc-upload.inf5.tinfoil.sh

  whisper-large-v3-turbo:
    repo: tinfoilsh/confidential-whisper-large-v3
    enclaves:
      - whisper.inf6.tinfoil.sh

  llama3-3-70b:
    repo: tinfoilsh/confidential-llama-qwen
    enclaves:
      - llama-qwen.inf8.tinfoil.sh

  qwen3-coder-480b:
    repo: tinfoilsh/confidential-llama-qwen
    enclaves:
      - llama-qwen.inf8.tinfoil.sh

  deepseek-r1-0528:
    repo: tinfoilsh/confidential-deepseek-r1-0528
    enclaves:
      - deepseek-r1-0528.inf9.tinfoil.sh

  gpt-oss-120b:
    repo: tinfoilsh/confidential-gpt-oss-120b
    enclaves:
      - gpt-oss-120b.inf5.tinfoil.sh

  gpt-oss-120b-free:
    repo: tinfoilsh/confidential-gpt-oss-120b-free
    enclaves:
      - gpt-oss-120b-free.inf5.tinfoil.sh

  qwen3-vl-30b:
    repo: tinfoilsh/confidential-qwen3-vl-30b
    enclaves:
      - qwen3-vl-30b.inf5.tinfoil.sh

  deepseek-v31-terminus:
    repo: tinfoilsh/confidential-deepseek-v31-terminus
    enclaves:
      - deepseek-v31-terminus.inf7.tinfoil.sh
    overload:
      max_requests_waiting: 75
      retry_after_minutes: 3
