routers:
  inference.tinfoil.sh:

models:
  nomic-embed-text:
    repo: tinfoilsh/confidential-nomic-embed-text
    enclaves:
      - confidential-nomic-embed-text.tinfoil.containers.tinfoil.sh

  doc-upload:
    repo: tinfoilsh/confidential-doc-upload
    enclaves:
      - confidential-doc-upload.tinfoil.containers.tinfoil.sh

  whisper-large-v3-turbo:
    repo: tinfoilsh/confidential-whisper-large-v3
    enclaves:
      - whisper.inf6.tinfoil.sh

  voxtral-small-24b:
    repo: tinfoilsh/confidential-voxtral-small-24b
    enclaves:
      - voxtral-small-24b.inf5.tinfoil.sh

  llama3-3-70b:
    repo: tinfoilsh/confidential-llama3-3-70b
    enclaves:
      - llama3-3-70b.inf5.tinfoil.sh

  deepseek-r1-0528:
    repo: tinfoilsh/confidential-deepseek-r1-0528
    enclaves:
      - deepseek-r1-0528.inf7.tinfoil.sh

  gpt-oss-120b:
    repo: tinfoilsh/confidential-gpt-oss-120b
    enclaves:
      - gpt-oss-120b.inf5.tinfoil.sh

  gpt-oss-120b-free:
    repo: tinfoilsh/confidential-gpt-oss-120b-free
    enclaves:
      - gpt-oss-120b-free.inf5.tinfoil.sh

  gpt-oss-safeguard-120b:
    repo: tinfoilsh/confidential-gpt-oss-safeguard-120b
    enclaves:
      - gpt-oss-safeguard-120b.inf5.tinfoil.sh

  qwen3-tts-1.7b:
    repo: tinfoilsh/confidential-qwen3-tts
    enclaves:
      - qwen3-tts.inf6.tinfoil.sh

  qwen3-vl-30b:
    repo: tinfoilsh/confidential-qwen3-vl-30b
    enclaves:
      - qwen3-vl-30b.inf5.tinfoil.sh

  kimi-k2-thinking:
    repo: tinfoilsh/confidential-kimi-k2-thinking
    enclaves:
      - kimi-k2-thinking.inf9.tinfoil.sh

  kimi-k2-5:
    repo: tinfoilsh/confidential-kimi-k2-5
    enclaves:
      - kimi-k2-5.inf8.tinfoil.sh

  qwen2-5-05b:
    repo: tinfoilsh/confidential-qwen2-5-05b
    enclaves:
      - title-model.tinfoil.functions.tinfoil.sh

  websearch:
    repo: tinfoilsh/confidential-websearch
    enclaves:
      - websearch.tinfoil.functions.tinfoil.sh
