shim-version: v0.3.10@sha256:825cfafbc6dde8967ac60e44264f4686fcf2ed33fae112ab4b1c69c6673cdc8e
cvm-version: 0.6.1
cpus: 8
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-model-router:0.0.45"
    env:
      - DOMAIN
