shim-version: v0.3.19@sha256:e67b8cd0ed61d646911414da0faa378320da7e8b162e399f6ee8b263f45f3f8e
cvm-version: 0.6.7
cpus: 8
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  tls-wildcard: true

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-model-router:0.0.61"
    env:
      - DOMAIN
      - REFRESH_INTERVAL: "1m"
