shim-version: v0.3.17@sha256:6dff221ec3c4de5c4f44472bc21b47574b7d118902aaa0a55fd367eeaa1f33c5
cvm-version: 0.6.7
cpus: 8
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  tls-wildcard: true

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-model-router:0.0.57"
    env:
      - DOMAIN
      - REFRESH_INTERVAL=1m
