shim-version: v0.3.1@sha256:ff2cc20df55d3a33c527052911871f3d1d4d16a1b708b15266fc0ced01c2c21a
cvm-version: 0.5.8
cpus: 8
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  publish-attestation: true
  tls-challenge: dns

containers:
  - name: "proxy"
    image: ""
    args: [
      "ghcr.io/tinfoilsh/confidential-model-router:0.0.27",
      "-d","$(awk -F': *' '$1~/^domain$/{print $2; exit}' /mnt/ramdisk/external-config.yml)",
    ]
