shim-version: v0.2.15@sha256:5ca748b384b78b7e686b57ca66d9b3c552038ebab2ce60305004f76e573a8458
cvm-version: 0.5.8
cpus: 8
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  publish-attestation: true
  tls-challenge: dns

containers:
  - name: "proxy"
    image: ""
    args: [
      "ghcr.io/tinfoilsh/confidential-model-router:0.0.23",
      "-d","$(awk -F': *' '$1~/^domain$/{print $2; exit}' /mnt/ramdisk/external-config.yml)",
    ]
