shim-version: v0.3.12@sha256:b81f2295ae6750d61e94f810ce24077360001b6ec795d13643f3170df29e304d
cvm-version: 0.6.2
cpus: 8
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-model-router:0.0.48"
    env:
      - DOMAIN
