shim-version: v0.2.5@sha256:ffdc7ca8e1a974c318533262c072b2c6c0871431b1e951fde7692388b5854cc3
cvm-version: 0.3.0
ovmf-version: 0.0.2
cpus: 16
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  publish-attestation: true
  tls-challenge: dns

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-inference-proxy:0.0.44"
