shim-version: v0.2.14@sha256:24d59ce41ad00a05ab5a37708b0d8b07a7d09abb1b74b75ee4862f688d093949
cvm-version: 0.5.8
cpus: 16
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  publish-attestation: true
  tls-challenge: dns

containers:
  - name: "proxy"
    image: ""
    args: [
      "ghcr.io/tinfoilsh/confidential-model-router:0.0.20",
      "-d","$(awk -F': *' '$1~/^domain$/{print $2; exit}' /mnt/ramdisk/external-config.yml)",
    ]
