shim-version: v0.2.13@sha256:adcaa4599ac473aaa91948dbe87f09d6d992710a95fd2e21fa2f339e45a9143b
cvm-version: 0.5.8
cpus: 16
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  publish-attestation: true
  tls-challenge: dns

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-model-router:0.0.17"
    args: ["-d", "$(awk -F': *' '$1~/^domain$/{print $2; exit}' /mnt/ramdisk/external-config.yml)"]
