shim-version: v0.4.0@sha256:86e5fe4bcbf673847322c7416d49580ba6e8b41e30166fe9b8a8512b4a90c7ee
cvm-version: 0.6.7
cpus: 8
memory: 16384

shim:
  listen-port: 443
  upstream-port: 8089
  tls-wildcard: true

containers:
  - name: "proxy"
    image: "ghcr.io/tinfoilsh/confidential-model-router:0.0.59"
    env:
      - DOMAIN
      - REFRESH_INTERVAL: "1m"
